iOS hooks

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -16,3 +16,11 @@ check_variable "IM_APP_CLIENT_ID"
 check_variable "IM_APP_CLIENT_SECRET"
 check_variable "CLOUD_PLAYER_KEY"
 check_variable "CLOUD_PLAYER_SECRET"
+
+# Check for changes to the KeyCenter file
+if git diff --cached --name-only | grep -q 'KeyCenter.swift'; then
+    echo "Error: Modifying the KeyCenter file is not allowed."
+    exit 1
+fi
+
+exit 0
